apiVersion: apps/v1
kind: Deployment
metadata:
  name: rangersapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rangersapp
  template:
    metadata:
      labels:
        app: rangersapp
    spec:
      containers:
        - name: rangersapp
          image: rangersapp:local
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /api/results/html
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
